server:
  port: 8080
spring:
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres?stringtype=unspecified&ApplicationName=tutorial
    username: postgres
    password: root

mybatis:
  mapper-locations: classpath:mapping/*Dao.xml
  type-aliases-package: com.fan.bean
